# Generated by Django 3.2 on 2021-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210416_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[('citrus', 'citrus'), ('electric', 'electric')], max_length=100),
        ),
    ]
