# Generated by Django 3.2 on 2021-04-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
